const FILM_COUNT_ALL_MOVIES = 24;
const FILM_COUNT_PER_STEP = 5;
const FILM_COUNT_TOP_RATED = 2;
const FILM_COUNT_MOST_COMMENTED = 2;


const COMMENT_MIN_COUNT = 0;
const COMMENT_MAX_COUNT = 5;

export {
  FILM_COUNT_ALL_MOVIES, FILM_COUNT_PER_STEP, FILM_COUNT_TOP_RATED,
  FILM_COUNT_MOST_COMMENTED, COMMENT_MIN_COUNT, COMMENT_MAX_COUNT
};
